[package]
name = "belajar_rust"
version = "0.1.0"
authors = ["fadilmuh22 <fadilmuh2002@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
